pkg/report/model/sarif.go
pkg/report/model/utils.go
pkg/report/sarif.go

Closes #
- after talking to SA team they have some asks for where certain information is displayed in the file
-
-
-

[BFO-330] Remove taxonomy, move category, fix 0-based indexing

---

assets/assets.go
kics.go
pkg/detector/terraform/terraform_detect.go
pkg/engine/inspector.go
pkg/engine/inspector_test.go
pkg/engine/mock/source.go
pkg/engine/source/filesystem.go
pkg/engine/source/filesystem_test.go
pkg/engine/source/source.go
pkg/remediation/scan.go
pkg/scan/client.go
pkg/scan/scan.go
pkg/scanner/scanner_test.go
test/queries_content_test.go
test/queries_test.go
test/similarity_id_test.go

[BFO-333] Modify query dir inputs

---

.github/dependabot.yml
assets/assets.go
pkg/engine/source/filesystem.go
pkg/scan/post_scan.go
pkg/scan/utils.go

Revert "[BFO-367] Perf optimizations: remove temp file extracting, skip query lookup in test dirs, skip custom lib lookup"

---

pkg/analyzer/analyzer.go
pkg/engine/provider/filesystem.go
pkg/kics/sink.go
pkg/parser/terraform/converter/default.go
pkg/parser/terraform/variables.go
pkg/scan/client.go

[BFO-441] Restrict to Terraform and parse variables.tf

---

pkg/report/model/sarif.go

[K9VULN-2969] Add hashing for fingerprint

---

pkg/report/model/sarif.go

[K9VULN-3039] Add comment about not changing tool name

---

pkg/report/model/sarif.go
pkg/report/model/sarif_test.go

We want to add the rule id to the description for easier visibility for customers.

[K9VULN-3373] Add rule id to full description

---

.gitignore
dd-iac-scan.config

I want to test the e2e exclusions functionality specifically for PR comments/code-update to make sure that the config level exclusions are properly excluded since we do file filtering for only files changed in the code updates.

[K9VULN-3784] Add exclusions in config file

---

assets/queries/terraform/aws/dms_endpoint_no_ssl_configured/query.rego
assets/queries/terraform/aws/imdsv1_is_enabled/query.rego
assets/queries/terraform/aws/neptune_snapshots_not_encrypted/query.rego
assets/queries/terraform/aws/s3_bucket_without_versioning/query.rego
assets/queries/terraform/aws/sagemaker_direct_internet_access_enabled/query.rego
pkg/detector/terraform/terraform_detect.go
pkg/detector/terraform/terraform_detect_test.go
pkg/engine/vulnerability_builder.go
pkg/engine/vulnerability_utils.go
pkg/model/model.go
pkg/model/summary.go
pkg/report/model/sarif.go
pkg/report/model/sarif_test.go
pkg/report/remediations/remediations_helper.go
pkg/report/remediations/remediations_helper_test.go

This PR has all the changes needed to make the AWS remediations work properly.

[K9VULN-4724] AWS remediations

---

pkg/detector/terraform/terraform_detect.go

Handle functions as nested attrs

---

assets/queries/terraform/aws/imdsv1_is_enabled/query.rego

[K9VULN-5242] Fix encoding in inserted metadata_options

---

pkg/report/model/sarif.go

[K9VULN-5326] Moving rule id to the end of the description

---

pkg/report/model/sarif.go
pkg/report/model/utils.go

add count as tag to be used in sarif processing 

K9VULN-7107 Add tag for scanned file count

---

pkg/engine/inspector.go
pkg/engine/utils/modules.go

Refs: K9VULN-6987
Closes #
- We would like to have observability over the module support
- Introduce proper logging
-
-

feat: added a few logs to the modules POC

---

pkg/model/model_yaml.go
pkg/model/model_yaml_test.go

fix crashes of the iac-scanning service due to stack overflow errors

K9VULN-7748 fix stack overflow error due to circular yaml references

---

documentation/rules/terraform/aws/team_tag_not_present.md
documentation/rules/terraform/azure/team_tag_not_present.md
documentation/rules/terraform/gcp/team_label_not_present.md

- Updated some rule names earlier, directly in the metadata. The docs also need to be modified
- Change the markdowns directly
-
-

[K9VULN-7958] Changed the name of the rules for the docs

---

assets/queries/cicd/github/run_block_injection/metadata.json
assets/queries/cicd/github/script_block_injection/metadata.json
assets/queries/cicd/github/unpinned_actions_full_length_commit_sha/metadata.json
assets/queries/cicd/github/unsecured_commands/metadata.json
documentation/frontmatter.yaml
documentation/list.json
documentation/resources.json
documentation/rules/cicd/github/run_block_injection.md
documentation/rules/cicd/github/script_block_injection.md
documentation/rules/cicd/github/unpinned_actions_full_length_commit_sha.md
documentation/rules/cicd/github/unsecured_commands.md
rules_generator/classes/CodeProcessor.py
rules_generator/classes/Coordinator.py
rules_generator/classes/RulesGenerator.py
rules_generator/classes/models/Output.py
rules_generator/main.py

Closes #
- Our documentation does not match the DD docs criteria. We need to make it better
- Use a LLM to enhance the docs
-
-

[K9VULN-8217] Documentation enhancement

---

pkg/engine/source/filesystem.go
pkg/featureflags/evaluator.go
pkg/featureflags/local_evaluator.go

- We need to test the rules before we allow the clients to use them
- Add a feature flag to filter by platform
-
-

Add FF to filter platforms

---

assets/queries/k8s/authorization_mode_set_to_always_allow/metadata.json
frameworks_sync/README.md
frameworks_sync/requirements.txt
frameworks_sync/sync_framework_mappings.py

Tested locally to ensure:
New controls are added
Deleted controls are removed
Updated controls are updated 
Unnecessary modifications are not made

K9VULN-8482 Add script to sync compliance frameworks

---

pkg/report/model/sarif.go
pkg/report/model/utils.go

Closes #
- We want the customers to be able to filter by platform
- Add a platform tag in the rule properties
-
-

Add platform tag to sarif

---

internal/console/helpers/helpers.go
internal/console/pre_scan.go
pkg/engine/inspector.go
pkg/engine/provider/extract.go
pkg/engine/provider/filesystem.go
pkg/engine/secrets/inspector.go
pkg/engine/source/filesystem.go
pkg/kics/resolver_sink.go
pkg/kics/service.go
pkg/kics/sink.go
pkg/kuberneter/kuberneter.go
pkg/kuberneter/utils.go
pkg/parser/terraform/converter/default.go
pkg/scan/post_scan.go
pkg/scan/preview_secrets_mask.go
pkg/scan/scan.go
pkg/scanner/scanner.go
pkg/utils/ansible_vault.go

Just some cleanup of dead commented out code

chore: Remove commented out dead code
