pkg/report/model/sarif.go
pkg/report/model/sarif_test.go
pkg/report/model/utils.go

Static Analysis doesn't have a separation between name and id so in this case we want to use the name as the id since that is the friendly identifiable attribute that is displayed downstream.

[BFO-336] Use KICS rule name as id

---

pkg/report/model/utils.go

SA sarif processor expects the scan duration to be an int instead of a float.

[BFO-340] Convert scan duration to int instead of float

---

internal/console/scan.go
kics.go
pkg/engine/inspector.go
pkg/engine/inspector_test.go
pkg/engine/vulnerability_builder.go
pkg/engine/vulnerability_builder_test.go
pkg/model/model.go
pkg/remediation/scan.go
pkg/scan/client.go
pkg/scan/metadata.go
pkg/scan/post_scan.go
pkg/scan/post_scan_test.go
test/queries_content_test.go

We want to add some analyzer metadata about the run to the output from the KICS tool.

[BFO-342] Add analyzer stats to scan execution

---

pkg/model/source_code.go
pkg/report/model/sarif.go
pkg/report/sarif.go
pkg/report/sarif_test.go

We want to specify the run type- code update or full scan in the SARIF results so that we are able to filter on them downstream.

[K9VULN-2808] Set run type in SARIF

---

pkg/model/source_code.go
pkg/report/model/sarif.go
pkg/report/model/sarif_test.go
pkg/report/model/utils.go
pkg/report/sarif.go

As part of ensuring unique results get processed correctly we want to handle full_repo scans vs code_update scans and ensure that the downstream processing correctly dedupes so that we don't inadvertently skip processing results because we think they are duplicates.
The logic here is that for full-repo we will tie the run date to ensure that we treat individual dates as unique results and for code-updates scope it to the commit sha.

[K9VULN-2969] Add DATADOG_FINGERPRINT to SARIF results

---

assets/queries/terraform/aws/iam_access_analyzer_not_enabled/query.rego

We seem to be flagging on non aws-resources for the `iam_access_analyzer_not_enabled` rule. 
From what I can tell this could be happening because there is an aws resource in the document file that is triggering but then because this resource contains `aws` in the name it is also being associated with the violation.

[K9VULN-2829] Modify rego query to check for aws_ resource types

---

pkg/scan/metadata.go
pkg/scan/post_scan.go

As part of production readiness we want to be able to report metrics on certain information including the breakdown of violations by severity.

[K9VULN-3337] Add severity breakdown to returned scan metadata

---

assets/queries/terraform/aws/s3_bucket_without_restriction_of_public_bucket/query.rego
assets/queries/terraform/aws/s3_bucket_without_restriction_of_public_bucket/test/positive1.tf

We got some customer feedback that because restrict_public_buckets defaults to false we should ideally not flag it as a violation when it is not defined.
This removes the rego check that was enforcing that restrict_public_buckets be present AND false. We now only fail this rule if the value is explicitly set to true.

[K9VULN-3372] Clean up rule logic for restrict_public_buckets

---

kics.go
pkg/parser/parser.go
pkg/parser/terraform/terraform.go
pkg/scan/client.go
pkg/scan/post_scan.go
pkg/scan/scan.go
pkg/scan/utils.go

This pr adds some logs around exclusion usage within the IaC scanner. Specifically we log the various types of exclusions as well as some additional information like branch and repository.
To do this I also needed to pipe through some information as well as make other pieces of information retrievable in the path analysis/scan processing.

[K9VULN-3826] Add explicit logs for exclusions

---

kics.go
pkg/scan/client.go
pkg/scan/pre_scan.go

With the way we download/clone the repository files for IaC scanning and the fact that we expect the config file to be located at the root of the repository we were previously assuming that KICS is being run in the same directory as the repository root. However we actually download the files to a tmp directory and then run KICS on that dir which means the KICS base dir and the repository base dir don't match up.
For config file exclusions we ONLY look at the base dir and so we aren't properly finding the config file.
This change now prepends the correct tmp dir to the path where we look for the config file to ensure we can properly identify it if it is present.

[K9VULN-3784] Use root path to properly find config file for exclusions

---

assets/queries/terraform/aws/alb_listening_on_http/test/positive2.tf
assets/queries/terraform/azure/app_service_managed_identity_disabled/test/negative1.tf
assets/queries/terraform/azure/app_service_managed_identity_disabled/test/positive1.tf
internal/tracker/ci.go
internal/tracker/ci_test.go
pkg/kics/resolver_sink.go
pkg/kics/service.go
pkg/kics/sink.go
pkg/kics/terraform_utils.go
pkg/model/summary.go
pkg/scan/metadata.go
pkg/scan/post_scan.go
pkg/scan/post_scan_test.go

For tracking purposes it is helpful to keep track of all the Terraform resources found/scanned in the files of each run.
This PR does the work necessary to count the resources as the files are being processed and wire the count metadata in the various places needed to eventually surface it back to the invoking caller in dd-source.
Note for reviewers: There were a few formatting issues/linting errors I found during this PR so they are included in this changeset as well.

[K9VULN-3921] Add resources scanned to emitted metadata

---

assets/generator/directory/main.go
assets/queries/terraform/gcp/legacy_networks_exist_for_project/metadata.json
assets/queries/terraform/gcp/legacy_networks_exist_for_project/query.rego
assets/queries/terraform/gcp/legacy_networks_exist_for_project/test/negative.tf
assets/queries/terraform/gcp/legacy_networks_exist_for_project/test/negative_2.tf
assets/queries/terraform/gcp/legacy_networks_exist_for_project/test/positive.tf
assets/queries/terraform/gcp/legacy_networks_exist_for_project/test/positive_expected_result.json
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/metadata.json
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/query.rego
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/test/negative.tf
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/test/positive.tf
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/test/positive_expected_result.json
dd-iac-scan.config

As part of continuing to match coverage with the internal usage of Checkov at Datadog this PR adds the rules identified as missing from the current implementation of Checkov happening in [cloud-tf-ci](https://github.com/DataDog/cloud-tf-ci/blob/a8820543fd4aaad74baf79927150560445bfd13f/src/tools/job/checkov-config.yml).
There are [2 rules](https://docs.google.com/spreadsheets/d/1exbE0FBv9LTNS9Vylbm8xCBlX9A2zq5saXkX7RNw83I/edit?gid=517370387#gid=517370387) missing which this PR adds coverage for.
Checkov ID | Rule Description | KICS ID | KICS Rule Description
-- | -- | -- | --
CKV2_GCP_2 | Ensure legacy networks do not exist for a project | 550e8400-e29b-41d4-a716-446655440000 | Ensure legacy networks do not exist for a project
CKV2_GCP_3 | Ensure that there are only GCP-managed service …

[K9VULN-4000] Add missing cloud-tf-ci rules for coverage

---

pkg/report/model/sarif.go
pkg/report/model/sarif_test.go
pkg/report/model/utils.go
test/e2e/e2e_test.go

We received feedback from Kobold and Org2 that it would be nice to filter and view results based on resource type and resource name. 
In order to do this we need to enrich the SARIF file produced with these details for each result and then process and parse in the SARIF processing.
This PR adds the attributes to the SARIF file.

[K9VULN-4043] Add resource name and resource type to SARIF results

---

assets/queries/terraform/aws/iam_password_does_not_require_uppercase/metadata.json
assets/queries/terraform/azure/postgres_enforce_ssl_connection_disabled/metadata.json
assets/queries/terraform/azure/storage_account_not_forcing_https/metadata.json
assets/queries/terraform/azure/storage_account_not_forcing_https/query.rego
assets/queries/terraform/azure/storage_account_not_forcing_https/test/negative.tf
assets/queries/terraform/azure/storage_account_not_forcing_https/test/negative1.tf
assets/queries/terraform/azure/storage_account_not_forcing_https/test/positive.tf
assets/queries/terraform/gcp/pubsub_topic_is_public/metadata.json
assets/queries/terraform/gcp/service_has_non_gcp_managed_service_account_keys/metadata.json

Customer reported that the rule appears to be using an outdated Terraform attribute. This PR updates the rule to check for the correct attribute. Because it defaults to true we also remove the check for missing attribute.
As part of pulling the current ruleset I noticed we have some duplicated rule ids so also cleaning those up.

[K9VULN-3905] Address reported false positive in 12944ec4-1fa0-47be-8b17-42a034f937c2 and duplicated rule ids

---

pkg/report/model/sarif.go

As part of reducing the size of the SARIF file we generate there are a few attributes currently written which are not needed.
- Result Kind
- This is used in KICS to denote failures vs informational traces but is not used within the ci-sarif-processor at all
- Result Message -> Platform
- This is used in KICS to identify which IaC platform the result is part of. Because we are focusing on Terraform specifically this is not needed. Additionally the processing pipeline also parses out the file type so we already have another way of associating these results to Terraform

[K9VULN-3999] Remove unused attributes from SARIF to help reduce size of file

---

pkg/detector/default_detect.go
pkg/detector/helm/helm_detect.go
pkg/detector/helper.go
pkg/detector/terraform/terraform_detect.go
pkg/report/model/sarif.go

We were getting errors like `Failed to detect Terraform line, query response: %s` for a variety of reasons.
This PR attempts to address each of the edge cases that caused this.
* SearchKey wasn't properly sanitized in some cases so logic to match on the resource was erroring out
* Search keys with {} and [{{label}}] were failing to properly be matched
* Handle aws_something[resource_name] search keys
* Handle raw bracketed values (e.g., [abc]) vs placeholders (e.g., [{{var}}]) correctly
* Support Terraform resource matching within lists
* Handle replacement remediation case where it is an entire line that needs to be replaced and not just an in-line value
* For GCP, handle resource paths with "/" and not just "."
* Support multiple 'before' values separated by 'or' in remediation
* Handle …

[K9VULN-4722] Fix Terraform Line Detection Errors

---

pkg/detector/terraform/terraform_detect.go
pkg/detector/terraform/terraform_detect_test.go
pkg/report/remediations/remediations_helper.go
pkg/report/remediations/remediations_helper_test.go
pkg/report/remediations/utilities.go

There are a few motivations for the changes here:
1. Reduce Function Complexity- break up the large functions that were doing everything
2. Centralize Constant Return Values- reduce some duplication in the values being returned that were constanst (undetected, empty, etc)
3. Cleanup Inline Comments- outdated from previous work
4. Log Errors Using Logger, Not fmt.Printf
5. Naming improvements (my white whale 🐋)
6. Handle case where type assertions may panic with unexpected input
7. Refactor the three main RemediationType cases into their own clearly named helpers
8. Split Block-Style and List-Style Matching
9. Add missing tests for edge cases

[K9VULN-4960] Refactor and add tests

---

internal/console/helpers/helpers.go
internal/console/helpers/helpers_test.go
kics.go
pkg/report/asff.go
pkg/report/asff_test.go
pkg/report/code_climate.go
pkg/report/code_climate_test.go
pkg/report/csv.go
pkg/report/csv_test.go
pkg/report/cyclonedx.go
pkg/report/cyclonedx_test.go
pkg/report/gitlab_sast.go
pkg/report/gitlab_sast_test.go
pkg/report/html.go
pkg/report/html_test.go
pkg/report/json.go
pkg/report/json_test.go
pkg/report/junit.go
pkg/report/junit_test.go
pkg/report/model/sarif.go
pkg/report/model/sarif_test.go
pkg/report/pdf.go
pkg/report/pdf_test.go
pkg/report/sarif.go
pkg/report/sonarqube.go
pkg/scan/client.go
pkg/scan/post_scan.go
pkg/scan/post_scan_test.go

We want to make remediations in SARIF a gateable feature. This PR adds the logic to wire up the associated boolean flag into the scan execution and controls whether we populate the fixes into the SARIF or not.

[K9VULN-4961] Make remediations gateable

---

assets/queries/terraform/aws/ami_owner_missing/metadata.json
assets/queries/terraform/aws/ami_owner_missing/query.rego
assets/queries/terraform/aws/ami_owner_missing/test/negative.tf
assets/queries/terraform/aws/ami_owner_missing/test/positive.tf
assets/queries/terraform/aws/ami_owner_missing/test/positive_expected_result.json

As part of evaluating the existing SAST Terraform rules we identified that one was missing from the existing KICS coverage.
The missing rule is [ami-missing-owners](https://app.datadoghq.com/ci/code-analysis/static-analysis/default-rulesets/terraform-aws?currentTab=overview&ruleName=ami-missing-owners).
This PR adds the relevant rule and examples.

[K9VULN-5006] Add AMI owner missing rule

---

assets/libraries/terraform.rego

We weren't handling the case when a resourceName contains a variable reference like var.name which meant that we were populating resource names like that. We now fallback to the resource definition name in the case that the inferred name contains a .
Eventually we will want to account for this with things like variable and locals resolution but this should fix the issue for now.

[K9VULN-5045] Handle variable references in resource name

---

assets/queries/terraform/aws/team_tag_not_present/metadata.json
assets/queries/terraform/aws/team_tag_not_present/query.rego
assets/queries/terraform/aws/team_tag_not_present/test/negative4.tf
assets/queries/terraform/gcp/team_label_not_present/metadata.json

We got feedback from Fundapps that the links were going nowhere and we were marking resources correctly using tags within a merge function as invalid.

[K9VULN-5085] Feedback on team tags rule per Fundapps

---

assets/queries/terraform/gcp/cloud_dns_without_dnssec/query.rego
assets/queries/terraform/gcp/cloud_dns_without_dnssec/test/positive1.tf
assets/queries/terraform/gcp/cloud_dns_without_dnssec/test/positive2.tf
assets/queries/terraform/gcp/cloud_dns_without_dnssec/test/positive_expected_result.json

One of the 7 rules that Checkov flags but we don't is this one.
Basically the logic we had and the logic Checkov looks for is quite different:
Checkov:
Aspect | Behavior
-- | --
Resource | google_dns_managed_zone
Key to check | dnssec_config[0].state
Expected values | "on" or "transfer"
Missing key | Implicitly fails unless exempted
Exception condition | If visibility = private, return UNKNOWN (don’t check DNSSEC)
</body></html>
IaC Scanning:
Aspect | Behavior
-- | --
Resource | google_dns_managed_zone
Key to check | resource.dnssec_config.state, or array-style lookup
Expected values | "on" only
Missing key | Requires explicit == null or not valid_key(...)
Exception condition | None — visibility not checked
</body></html>
This PR modifies the logic in our rego check to more closely mimic …

[K9VULN-5254] Fix GCP DNSSec rule

---

assets/libraries/common.rego
assets/libraries/terraform.rego
assets/queries/terraform/aws/s3_bucket_access_to_any_principal/query.rego
assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/positive3.tf
assets/queries/terraform/aws/s3_bucket_access_to_any_principal/test/positive_expected_result.json
pkg/engine/inspector.go

As part of investigating the diff between Checkov and our Iac Scanning results there are 7 rules which aren't generating violations.
This PR addresses one of the rules:
Checkov ID | Description | KICS ID
-- | -- | --
CKV_AWS_70 | Ensure S3 bucket does not allow an action with any Principal | 7af43613-6bb9-4a0e-8c4d-1314b799425e
The problem is that our rego logic wasn't setup to handle jsonencoded values like the one present in the cloud-inventory file that is violating in the checkov results.
The fix ended up being more complicated however because I need to basically parse and convert the hcl into the AST objects to pass to the rego execution myself as well as handle variable values because they would break the json decoding logic. 
This PR therefore uses the hclsyntax and hclparse …

[K9VULN-5251] Handle jsonencode in policy statements

---

assets/queries/terraform/gcp/shielded_vm_disabled/query.rego
assets/queries/terraform/gcp/shielded_vm_disabled/test/positive1.tf

This rule wasn't properly handling objects and arrays as well as was using different logic than the Checkov implementation.

[K9VULN-5258] Change Shielded VM logic to properly flag

---

assets/libraries/terraform.rego
pkg/report/model/sarif.go

Per [#incident-38662](https://dd.enterprise.slack.com/archives/C08TB0R9NQ5) we need to make the fingerprint hash NOT be run type or date specific.
The fingerprint hash will now just be an encoded string representing the repo, filepath, violation start line and rule id.

[K9VULN-5367] Update fingerprint hash to be location and rule based only

---

assets/queries/terraform/aws/sensitive_port_is_exposed_to_entire_network/query.rego
assets/queries/terraform/aws/unknown_port_exposed_to_internet/query.rego

This rule was being overly aggressive and not differentiating between TCP and UDP cases properly. Additionally we weren't handling the unknown ports case properly either.

[K9VULN-5517] Address false positives in sensitive ports rule

---

kics.go
test/e2e/e2e_test.go

- Stop iac-scanning crashes due to kics errors
- Remove fatal log
- return error instead

K9VULN-6111 Remove fatal log and have kics return error

---

internal/constants/constants.go

In the constants.go, the url previously pointing the kics website is now pointing our docs
Refs: K9VULN-6230
Closes #
- The KICS URL needs to be removed from the rules as it is no longer necessary. Now that we have better documentation, the URL can be swapped out.
- Changed the constant
-
-

[K9VULN-6230] Changed URL to our docs

---

assets/queries/terraform/aws/alb_not_dropping_invalid_headers/query.rego

The resourceType was incorrectly set due to a typo.
Refs: incident-41687

[incident-41687] fix typo in resource type for rule `alb_not_dropping_invalid_headers`

---

.github/workflows/ci-testing.yaml
assets/assets.go
assets/queries/cicd/github/run_block_injection/query.rego
assets/queries/cicd/github/run_block_injection/test/positive1.yaml
assets/queries/cicd/github/script_block_injection/query.rego
assets/queries/cicd/github/unpinned_actions_full_length_commit_sha/query.rego
assets/queries/cicd/github/unsecured_commands/query.rego
pkg/detector/default_detect.go
pkg/detector/default_detect_test.go
pkg/detector/helm/helm_detect.go
pkg/detector/helper.go
pkg/detector/helper_test.go
pkg/detector/terraform/terraform_detect.go
pkg/detector/terraform/terraform_helper.go
pkg/detector/terraform/terraform_helper_test.go
pkg/parser/terraform/modules/modules.go
pkg/scan/client.go

Closes #
- Add a new framework to the IaC scanning
See the [enable framework page in Confluence](https://datadoghq.atlassian.net/wiki/spaces/Vulnerabil/pages/5458068295/Add+a+new+platform+framework)
- Enable the framework
This was done by changing the client.go and the assets.go.
- Ignore the non-Terraform files is for the ParseTerraformModules function that should not log a noisy error when trying to parse a file that is not even terraform. The function is not supposed to work, so it is no error.
- Added a multiline support in case the search key is a multiline string
This is because we are looking for the searchKey on each line, although a searchKey may me multiline. In this case, we look on multiple lines to try and find it. …

[K9VULN-7505] CICD PoC

---

pkg/utils/get_extension.go

- A lot of noise is generated at "Error" level by those logs that are juste expected when scanning full repos with collections of miscellaneous unscannable files.
- Those should be at the highest "Info" (or even "Debug"/removed altogether)

Reduce logging level for unsupported file ext from "Error" to "Info"

---

pkg/analyzer/analyzer.go
pkg/parser/yaml/parser.go

Added the reason to why we can't parse a yaml file
I submit this contribution under the Apach
e-2.0 license.

Added cause to failed yaml parsing

---

pkg/scan/metadata.go
pkg/scan/post_scan.go
pkg/scan/post_scan_test.go
test/e2e/e2e_test.go
test/e2e/fixtures/inline-disabled-rule.tf

Aggregate the count per rule in `ViolationBreakdowns` so it’s easier to report as a Distribution metric later.
Refs: K9VULN-6132

[K9VULN-6132] Change ViolationBreakdowns to count rule violations

---

pkg/kics/resolver_sink.go
pkg/resolver/helm/helm.go
pkg/resolver/helm/resolver.go

This PR enhances the logging in the Helm resolver for error handling and analysis following new detected [logs](https://app.datadoghq.com/logs/livetail?query=service%3Aiac-scanning%20%40org_id%3A%281300407896%20OR%20704937%20OR%201000065456%29&agg_m=%40repository&agg_m_source=base&agg_q=%40org_id%2C%40org_metadata.name&agg_q_source=base%2Cbase&agg_t=cardinality&cols=host%2Cservice&messageDisplay=inline&refresh_mode=paused&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=driveline&stream_sort=desc&top_n=500%2C15&top_o=top%2Ctop&viz=stream&x_missing=true%2Ctrue&from_ts=1759405308788&to_ts=1759406208788&live=false)

improve helm resolver logging with context-aware logger
